# Generated by Django 4.2.7 on 2024-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='wildfire_danger_forecasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueId', models.CharField(max_length=300)),
                ('AdminUnit', models.CharField(max_length=300)),
                ('CalFireIncident', models.CharField(max_length=300)),
                ('CanonicalUrl', models.CharField(max_length=300)),
                ('Counties', models.CharField(max_length=300)),
                ('CrewsInvolved', models.CharField(max_length=300)),
                ('Dozers', models.CharField(max_length=300)),
                ('Engines', models.CharField(max_length=300)),
                ('Extinguished', models.CharField(max_length=300)),
                ('Fatalities', models.CharField(max_length=300)),
                ('Featured', models.CharField(max_length=300)),
                ('Final', models.CharField(max_length=300)),
                ('Helicopters', models.CharField(max_length=300)),
                ('Injuries', models.CharField(max_length=300)),
                ('Latitude', models.CharField(max_length=300)),
                ('Location', models.CharField(max_length=300)),
                ('Longitude', models.CharField(max_length=300)),
                ('MajorIncident', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=300)),
                ('PercentContained', models.CharField(max_length=300)),
                ('PersonnelInvolved', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('Started', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=300)),
                ('Updated', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
    ]
