# Generated by Django 4.2.7 on 2024-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='CrewsInvolved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Dozers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Engines',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Extinguished',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Fatalities',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Final',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Helicopters',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Longitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='PercentContained',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='PersonnelInvolved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Prediction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='Status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wildfire_danger_forecasting',
            name='UniqueId',
            field=models.CharField(max_length=200),
        ),
    ]
